- CHANGELOG.md
- nflow-engine/src/main/java/com/nitorcreations/nflow/engine/internal/dao/ExecutorDao.java
- nflow-engine/src/main/java/com/nitorcreations/nflow/engine/internal/dao/WorkflowInstanceDao.java
- nflow-engine/src/main/java/com/nitorcreations/nflow/engine/internal/executor/WorkflowStateProcessor.java
- nflow-engine/src/main/java/com/nitorcreations/nflow/engine/internal/storage/db/H2DatabaseConfiguration.java
- nflow-engine/src/main/java/com/nitorcreations/nflow/engine/internal/storage/db/MysqlDatabaseConfiguration.java
- nflow-engine/src/main/java/com/nitorcreations/nflow/engine/internal/storage/db/PgDatabaseConfiguration.java
- nflow-engine/src/main/java/com/nitorcreations/nflow/engine/internal/storage/db/SQLVariants.java
- nflow-engine/src/main/java/com/nitorcreations/nflow/engine/internal/workflow/StateExecutionImpl.java
- nflow-engine/src/main/java/com/nitorcreations/nflow/engine/workflow/definition/AbstractWorkflowDefinition.java
- nflow-engine/src/main/java/com/nitorcreations/nflow/engine/workflow/instance/WorkflowInstanceAction.java
- nflow-engine/src/main/resources/scripts/db/h2.create.ddl.sql
- nflow-engine/src/main/resources/scripts/db/mysql.create.ddl.sql
- nflow-engine/src/main/resources/scripts/db/mysql.legacy.create.ddl.sql
- nflow-engine/src/main/resources/scripts/db/postgresql.create.ddl.sql
- nflow-engine/src/main/resources/scripts/db/update-1.2.0-x/h2.update.ddl.sql
- nflow-engine/src/main/resources/scripts/db/update-1.2.0-x/mysql.legacy.update.ddl.sql
- nflow-engine/src/main/resources/scripts/db/update-1.2.0-x/mysql.update.ddl.sql
- nflow-engine/src/main/resources/scripts/db/update-1.2.0-x/postgresql.update.ddl.sql
- nflow-engine/src/test/java/com/nitorcreations/nflow/engine/internal/dao/ExecutorDaoTest.java
- nflow-engine/src/test/java/com/nitorcreations/nflow/engine/internal/dao/WorkflowInstanceDaoTest.java
- nflow-engine/src/test/java/com/nitorcreations/nflow/engine/internal/executor/WorkflowStateProcessorTest.java
- nflow-engine/src/test/java/com/nitorcreations/nflow/engine/service/WorkflowInstanceServiceTest.java
- nflow-rest-api/src/main/java/com/nitorcreations/nflow/rest/v1/WorkflowInstanceResource.java
- nflow-rest-api/src/main/java/com/nitorcreations/nflow/rest/v1/converter/ListWorkflowInstanceConverter.java
- nflow-rest-api/src/main/java/com/nitorcreations/nflow/rest/v1/msg/Action.java
- nflow-rest-api/src/test/java/com/nitorcreations/nflow/rest/v1/WorkflowInstanceResourceTest.java
- nflow-rest-api/src/test/java/com/nitorcreations/nflow/rest/v1/converter/ListWorkflowInstanceConverterTest.java
- nflow-tests/src/test/java/com/nitorcreations/nflow/tests/CreditApplicationWorkflowTest.java
- nflow-tests/src/test/java/com/nitorcreations/nflow/tests/PreviewCreditApplicationWorkflowTest.java
Following types are supported currently:
- stateExecution - for actions created with normal execution. This is also set for old actions created before this feature.
- stateExecutionFailed - for actions that failed due throws exception or retry count was exceeded.
- externalChange - for state changes created manually via API.
- recovery - to indicate workflow was recovered after executor died.
> Add field nflow_instance_action.type.

- nflow-engine/src/test/java/com/nitorcreations/nflow/engine/service/SpringDummyTestWorkflow.java
- nflow-engine/src/test/java/com/nitorcreations/nflow/engine/service/WorkflowDefinitionServiceWithSpringTest.java
Eclipse includes the test code from included projects in the runtime of other projects. Use spring profiles to exclude some test workflows from autoscan.
> Workaroud eclipse bug/misfeature

- nflow-engine/src/main/resources/scripts/db/oracle.create.ddl.sql
This commit fixes issues with a missing column (root_workflow_id), wrong order in column definition (retries) and too long constraint name (nflow_archive_workflow_action_uniq).
> oracle schema fixes

- nflow-rest-api/src/main/java/io/nflow/rest/v1/WorkflowInstanceResource.java
nFlow ```CorsHeaderContainerResponseFilter``` does not currently process CORS preflight (```OPTIONS```) so workflow instances cannot be updated when nFlow Explorer is served from different URL than nFlow REST API.
This is because there're not resources behind the filter that could be called through ```CorsHeaderContainerResponseFilter```. This PR implements a dummy ```OPTIONS``` service.
The fix can be tested e.g. by running nFlow Explorer locally in port 9000 (```grunt serve```) and starting nFlow test server to port 7500 (```java -jar nflow-tests/target/nflow-tests-4.2.1-SNAPSHOT.jar```). Without this fix workflow instances cannot be updated.
> Fix CORS preflight handling for /v1/workflow-instance

- nflow-engine/src/main/java/io/nflow/engine/internal/dao/ExecutorDao.java
- nflow-engine/src/main/java/io/nflow/engine/internal/dao/WorkflowInstanceDao.java
In one deployment (with Java 7 and nFlow 3.3.0), H2 strangely returned 0 as column length:
- https://github.com/NitorCreations/nflow/blob/4.0.0/nflow-engine/src/main/java/io/nflow/engine/internal/dao/WorkflowInstanceDao.java#L139
- https://github.com/NitorCreations/nflow/blob/4.0.0/nflow-engine/src/main/java/io/nflow/engine/internal/dao/DaoUtil.java#L33
As a result, state transition failed (StringUtils.abbreviate() error "minimum abbreviation width 4").
The problem could not be reproduced in test deployment. This PR enables setting column lengths through properties, so that such problems can be at least evaded, if ever encountered again.
> Properties for explicit DB column max lengths

- nflow-engine/pom.xml
```EngineConfiguration``` uses ```jackson-annotations```, but there was no ```pom.xml``` dependency in ```nflow-engine```. As a result ```README.md``` quickstart instructions failed, because ```nflow-jetty``` got incompatible ```jackson-annotations``` as transitive dependency through ```swagger-core```.
> Add jackson-annotations dependency to nflow-engine

- nflow-engine/src/main/java/io/nflow/engine/internal/config/WorkflowLifecycle.java
- nflow-engine/src/main/java/io/nflow/engine/internal/executor/WorkflowDispatcher.java
- nflow-engine/src/main/resources/nflow-engine.properties
- nflow-engine/src/test/java/io/nflow/engine/internal/config/WorkflowLifecycleTest.java
- nflow-engine/src/test/java/io/nflow/engine/internal/executor/WorkflowDispatcherTest.java
- nflow-tests/src/test/java/io/nflow/tests/SkipAutoStartTest.java
Controls workflow definitions fetch from the database during Spring context load. This commit attempts to fix a problem with server in some cases starting before definitions are initialized from the database.
> Add nflow.autoinit parameter, defaults to true

- nflow-engine/pom.xml
- nflow-engine/src/main/java/io/nflow/engine/internal/config/EngineConfiguration.java
- nflow-engine/src/test/java/io/nflow/engine/internal/config/EngineConfigurationTest.java
- nflow-engine/src/test/java/io/nflow/engine/service/WorkflowDefinitionServiceWithSpringTest.java
- nflow-jetty/pom.xml
- nflow-metrics/pom.xml
- nflow-perf-test/pom.xml
- nflow-rest-api/pom.xml
- nflow-rest-api/src/test/java/io/nflow/rest/v1/config/RestConfigurationTest.java
- nflow-tests/pom.xml
- nflow-tests/src/test/java/io/nflow/tests/Swagger2MarkupTest.java
- pom.xml
Upgrade nflow to newly released Spring 5.0.1.RELEASE. Because this is a backward incompatible change, also bump nFlow version to 5.0.0.
Also update dependency versions.
This is a first of three PR's that aim to bring netty/webflux support to nFlow.
> Upgrade to Spring 5.0.1.RELEASE with nflow 5.0.0-SNAPSHOT

- nflow-server-common/src/main/java/io/nflow/server/spring/NflowStandardEnvironment.java
This allows overriding even system environment variables. Without this the tests fail on Fedora 28 that by default has the http://modules.sourceforge.net/ installed, which happens to use an environment variable called _ENV_ that happens to match the _env_ variable used by nflow to choose the active profile name.
Long term solution would be to namespace the variable to _nflow.env_
> Actually apply the override properties first

- nflow-jetty/src/main/java/io/nflow/jetty/config/NflowJettyConfiguration.java
This field is documented as:
"a list of comma separated package names where resources must be scanned+"
at https://cwiki.apache.org/confluence/display/CXF20DOC/Swagger2Feature.
> Add nflow.swagger.packages, default: io.nflow.rest

- release.sh
nFlow (REST) API link in wiki is broken:
https://github.com/NitorCreations/nflow/wiki
Jekyll used by Github pages has probably changed the way redirect_to -directive is used. Fix release.sh so redirects are generated properly in the future.
> Fix current (rest) apidocs redirects in release.sh

- apidocs/current/index.html
- rest-apidocs/current/index.html
nFlow (REST) API link in wiki is broken:
https://github.com/NitorCreations/nflow/wiki
Jekyll used by Github pages has probably changed the way redirect_to -directive is used. This file is generated by release.sh so another change for that.
> Fix (rest) apidocs redirect url for v5.0.0

- CHANGELOG.md
- nflow-engine/src/main/java/io/nflow/engine/workflow/definition/AbstractWorkflowDefinition.java
- nflow-engine/src/test/java/io/nflow/engine/workflow/definition/WorkflowDefinitionTest.java
Rationale: often we want a workflow instance to halt when reaching error state. Sometimes though, there's no harm in retrying forever, but it would be useful to send alarm periodically.
> Allow non-final error states

- .travis.yml
Oracle stopped supporting jdk10 in September 2018.
> Remove oraclejdk10 from travis build.

- nflow-engine/src/main/java/io/nflow/engine/internal/dao/ExecutorDao.java
- nflow-engine/src/main/java/io/nflow/engine/workflow/executor/WorkflowExecutor.java
- nflow-engine/src/main/resources/scripts/db/h2.create.ddl.sql
- nflow-engine/src/main/resources/scripts/db/mysql.create.ddl.sql
- nflow-engine/src/main/resources/scripts/db/mysql.legacy.create.ddl.sql
- nflow-engine/src/main/resources/scripts/db/oracle.create.ddl.sql
- nflow-engine/src/main/resources/scripts/db/postgresql.create.ddl.sql
- nflow-engine/src/main/resources/scripts/db/sqlserver.create.ddl.sql
- nflow-engine/src/main/resources/scripts/db/update-5.2.0-x/h2.update.ddl.sql
- nflow-engine/src/main/resources/scripts/db/update-5.2.0-x/mysql.legacy.update.ddl.sql
- nflow-engine/src/main/resources/scripts/db/update-5.2.0-x/mysql.update.ddl.sql
- nflow-engine/src/main/resources/scripts/db/update-5.2.0-x/oracle.update.ddl.sql
- nflow-engine/src/main/resources/scripts/db/update-5.2.0-x/postgresql.update.ddl.sql
- nflow-engine/src/main/resources/scripts/db/update-5.2.0-x/sqlserver.update.ddl.sql
- nflow-engine/src/test/java/io/nflow/engine/internal/dao/ExecutorDaoTest.java
- nflow-explorer/src/app/executors/executorTable.html
- nflow-explorer/src/app/executors/executorTable.js
- nflow-explorer/test/spec/workflow-definition/statisticsTestUtil.js
- nflow-rest-api-common/src/main/java/io/nflow/rest/v1/converter/ListWorkflowExecutorConverter.java
- nflow-rest-api-common/src/main/java/io/nflow/rest/v1/msg/ListWorkflowExecutorResponse.java
- nflow-rest-api-common/src/test/java/io/nflow/rest/v1/converter/ListWorkflowExecutorConverterTest.java
Add stopped field to nflow_executor table. Added corresponding field to REST API and UI.
This change requires at least a minor version number bump (-> 5.2.0).
> Add nflow_executor.stopped field

- CHANGELOG.md
- nflow-explorer/src/app/layout/header.html
- nflow-explorer/src/app/layout/layout.js
Making it easier to link nFlow Explorer to existing browser applications. You can now give optional returnUrl- and returnUrlLabel-parameters in Explorer opening URL (in server-part = before hashbang). The parameters control "return link" shown in the upper right corner of the UI.
Examples:
- Open Explorer front page and point return link to Slashdot with custom link label: http://localhost:9000?returnUrl=https%3A%2F%2Fwww.slashdot.org&returnUrlLabel=Return%20to%20my%20favourite%20place
- Open specific workflow instance (id 2) with the same return link as in the previous item: http://localhost:9000/?returnUrl=https%3A%2F%2Fwww.slashdot.org&returnUrlLabel=Return%20to%20my%20favourite%20place#!/workflow/2
> Support returnUrl- and returnUrlLabel-parameters

- nflow-engine/src/main/java/io/nflow/engine/internal/workflow/WorkflowDefinitionScanner.java
- nflow-engine/src/test/java/io/nflow/engine/internal/workflow/WorkflowDefinitionScannerTest.java
Add support for boxed primitives (Integer, Float etc) to @StateVar.
Initialize static variables in static initialization block in WorkflowDefinitionScanner.
> Support boxed primitives in @StateVar

- CHANGELOG.md
- pom.xml
Library and maven plugin updates:
- slf4j 1.7.26
- spring 5.1.5.RELEASE
- hamcrest 2.1
- reactor.netty 0.8.5.RELEASE
- swagger 1.5.22
- mockito 2.24.5
- io.dropwizard.metrics 4.0.5
- mysql-connector-java 8.0.15
- mssql-jdbc 7.2.1.jre8
- hikaricp 3.3.1
- maven-surefire 2.22.1
> Library updates

- CHANGELOG.md
- nflow-explorer/src/app/executors/executorTable.html
Use standard time formatting in tooltips in Executors page.
> nFlow explorer: Executors page tooltip time formatting

- CHANGELOG.md
- pom.xml
1.4.198 has issues with transactions: https://github.com/h2database/h2database/issues/1795
WorkflowInstanceDaoTest.pollNextWorkflowInstancesWithPartialRaceCondition
fails randomly causing one workflow instance to
be reserved by two pollers.
> Rollback h2 1.4.198 -> 1.4.197

- CHANGELOG.md
- nflow-jetty/src/main/java/io/nflow/jetty/StartNflow.java
- pom.xml
Update Jetty to 9.4.15.v20190215 and replace deprecated NCSARequestLog in StartNflow.java. See issue: https://github.com/NitorCreations/nflow/issues/289
> Replace deprecated NCSARequestLog with CustomRequestLog

- CHANGELOG.md
- nflow-engine/src/main/java/io/nflow/engine/internal/dao/ExecutorDao.java
When creating a new executor at startup, log its id, hostname and pid.
```
09.05.2019 12:47:23 INFO  [main] ngine.internal.dao.ExecutorDao - [user:] Joined executor group junit as executor 2 running on host 172.17.73.179 with process id 90761.
```
> Log executor info on startup.

- CHANGELOG.md
- nflow-engine/pom.xml
- nflow-engine/src/main/java/io/nflow/engine/internal/workflow/WorkflowInstancePreProcessor.java
- nflow-engine/src/main/java/io/nflow/engine/service/WorkflowDefinitionService.java
- nflow-explorer/pom.xml
- nflow-jetty/pom.xml
- nflow-metrics/pom.xml
- nflow-netty/pom.xml
- nflow-perf-test/pom.xml
- nflow-rest-api-common/pom.xml
- nflow-rest-api-jax-rs/pom.xml
- nflow-rest-api-spring-web/pom.xml
- nflow-server-common/pom.xml
- nflow-tests/pom.xml
- pom.xml
This will fix issue #311 by replacing references to WorkflowDefinition (which requires use of enum) with AbstractWorkflowDefinition (which works with any WorkflowState type classes).
> Replace references to WorkflowDefinition with AbstractWorkflowDefinition

- CHANGELOG.md
- pom.xml
- reactor.netty 0.8.8.RELEASE
- jetty 9.4.18.v20190429
- javassist 3.25.0-GA
- mysql-connector-java 8.0.16
- mssql-jdbc 7.2.2.jre8
- metrics 4.1.0
- spring 5.1.7.RELEASE
- hibernate.validator 6.0.15.Final
- cxf 3.3.2
- joda-time 2.10.2
- commons-lang3 3.9
- jackson 2.9.9
- junit 5.4.1
- mockito 2.27.0
> Dependency updates

- CHANGELOG.md
- nflow-engine/src/main/java/io/nflow/engine/NflowEngine.java
- nflow-engine/src/test/java/io/nflow/engine/NflowEngineTest.java
NflowEngine starts the nflow-engine and the caller doesn't need to use or worry about Spring setup.
> Add NflowEngine class for starting nflow-engine easily.

- CHANGELOG.md
- nflow-engine/src/main/resources/nflow-engine.properties
- nflow-tests/src/main/resources/local.properties
This is the only way to have both maridb and mysql jdbc drivers in the classpath at the same time
> No mariadb for mysql

- nflow-engine/src/main/resources/scripts/db/h2.create.ddl.sql
- nflow-engine/src/main/resources/scripts/db/sqlserver.create.ddl.sql
- nflow-engine/src/main/resources/scripts/db/update-5.6.0-x/h2.update.ddl.sql
- nflow-engine/src/main/resources/scripts/db/update-5.6.0-x/sqlserver.update.ddl.sql
Improvements for h2 create ddl, added trigger "if not exists" clause.
Improvements for mssql create ddl, added mssql style "if not exists" clauses.
Fix h2 and mssql latest update ddl (update-5.6.0-X) column `started` populating.
MSSQL scripts verified with MSSQL 2017-CU14-ubuntu and AzureSQL.
> Improvements and fixes for h2 and mssql ddl scripts

- CHANGELOG.md
- nflow-engine/src/main/java/io/nflow/engine/internal/dao/WorkflowInstanceDao.java
- nflow-engine/src/main/resources/nflow-engine.properties
- nflow-engine/src/test/resources/junit.properties
This makes it possible to revert to the multi update model even if the database needs it. This needs to be done to prevent MariaDB/Galera from having double executions.
> Add nflow.db.disable_batch_updates, default to false

- CHANGELOG.md
- nflow-engine/src/main/java/io/nflow/engine/internal/dao/WorkflowInstanceDao.java
- nflow-engine/src/main/java/io/nflow/engine/internal/executor/WorkflowStateProcessor.java
- nflow-engine/src/main/java/io/nflow/engine/internal/workflow/StateExecutionImpl.java
- nflow-engine/src/main/java/io/nflow/engine/internal/workflow/WorkflowInstancePreProcessor.java
- nflow-engine/src/main/java/io/nflow/engine/workflow/executor/StateVariableValueTooLongException.java
- nflow-engine/src/main/resources/nflow-engine.properties
- nflow-engine/src/test/java/io/nflow/engine/internal/dao/WorkflowInstanceDaoTest.java
- nflow-engine/src/test/java/io/nflow/engine/internal/executor/WorkflowDispatcherTest.java
- nflow-engine/src/test/java/io/nflow/engine/internal/executor/WorkflowStateProcessorFactoryTest.java
- nflow-engine/src/test/java/io/nflow/engine/internal/executor/WorkflowStateProcessorTest.java
- nflow-engine/src/test/java/io/nflow/engine/internal/workflow/StateExecutionImplTest.java
- nflow-engine/src/test/java/io/nflow/engine/workflow/WorkflowInstancePreProcessorTest.java
- nflow-engine/src/test/resources/junit.properties
Abbreviate or throw exception based on config.
> Check state variable value length when setting variable.

- nflow-explorer/Gruntfile.js
- nflow-explorer/README.md
- nflow-explorer/package-lock.json
- nflow-explorer/package.json
- nflow-explorer/test/README.md
- nflow-explorer/test/it/endpointSelection.spec.js
- nflow-explorer/test/it/frontPage.spec.js
- nflow-explorer/test/it/pageobjects/searchPage.js
- nflow-explorer/test/it/pageobjects/workflowDefinitionPage.js
- nflow-explorer/test/it/pageobjects/workflowPage.js
- nflow-explorer/test/protractor.conf.js
- migrate from grunt-autofixer to grunt-postcss (fixes diff-library vulnerability warning)
- migrate from grunt-selenium-standalone to direct usage of selenium-standalone when running Protractor tests (fixes hoek- and cryptiles-library vulnerability warning)
- fix rotten Protractor tests so that having any dependency to selenium makes any sense
> Fix Explorer build tool dependency vulnerability warnings (from github)

- CHANGELOG.md
- nflow-engine/src/main/java/io/nflow/engine/internal/dao/WorkflowInstanceDao.java
- nflow-engine/src/main/java/io/nflow/engine/workflow/definition/BulkWorkflow.java
- nflow-engine/src/main/java/io/nflow/engine/workflow/definition/StateExecution.java
- nflow-engine/src/main/java/io/nflow/engine/workflow/instance/QueryWorkflowInstances.java
- nflow-engine/src/test/java/io/nflow/engine/internal/dao/WorkflowInstanceDaoTest.java
- nflow-engine/src/test/java/io/nflow/engine/internal/workflow/StateExecutionImplTest.java
- nflow-tests/src/main/java/io/nflow/tests/demo/workflow/FibonacciWorkflow.java
- nflow-tests/src/test/java/io/nflow/tests/ChildWorkflowTest.java
Noticed at customer where bulk workflow parent that had ~2k children spent 99% of time by calling `fillState` for each of the child instances - and the values where never needed for anything.
> Honor the includeCurrentStateVariables in the QueryWorkflowInstances

- nflow-engine/src/main/java/io/nflow/engine/internal/dao/PollingBatchException.java
- nflow-engine/src/main/java/io/nflow/engine/internal/dao/PollingRaceConditionException.java
- nflow-engine/src/main/java/io/nflow/engine/internal/dao/WorkflowInstanceDao.java
- nflow-engine/src/main/java/io/nflow/engine/internal/executor/WorkflowDispatcher.java
- nflow-engine/src/test/java/io/nflow/engine/internal/dao/WorkflowInstanceDaoTest.java
- Fetch optimistic locked list of workflow instance ids in separate transaction from the modify phase. This should reduce the risk of deadlocks in databases.
- Also rework code so that if batch returns unsupported values we switch to non-batch usage.
> Tune workflow polling.

- nflow-engine/src/main/java/io/nflow/engine/internal/dao/WorkflowInstanceDao.java
- nflow-engine/src/main/java/io/nflow/engine/service/WorkflowInstanceService.java
- nflow-engine/src/test/java/io/nflow/engine/internal/dao/WorkflowInstanceDaoTest.java
- nflow-rest-api-common/src/main/java/io/nflow/rest/v1/ResourceBase.java
- nflow-rest-api-jax-rs/src/main/java/io/nflow/rest/v1/jaxrs/WorkflowInstanceResource.java
- nflow-rest-api-jax-rs/src/test/java/io/nflow/rest/v1/jaxrs/WorkflowInstanceResourceTest.java
- nflow-rest-api-spring-web/src/main/java/io/nflow/rest/v1/springweb/WorkflowInstanceResource.java
The main table query is still done synchronously, but additional queries are done on the stream lowering latency.
Should help with explorer UI, especially if it is later updated to process results lines as they arrive.
> Stream results out of rest api. 

- nflow-engine/src/main/java/io/nflow/engine/internal/executor/WorkflowStateProcessor.java
When this error happens, the instance id is of interest to anyone trying to debug the issue.
> Make an error message more informative by adding the instance id

- CHANGELOG.md
- nflow-netty/src/test/java/io/nflow/netty/StartNflowTest.java
- nflow-rest-api-spring-web/pom.xml
- nflow-rest-api-spring-web/src/main/java/io/nflow/rest/config/springweb/SchedulerService.java
- nflow-rest-api-spring-web/src/main/java/io/nflow/rest/v1/springweb/MaintenanceResource.java
- nflow-rest-api-spring-web/src/main/java/io/nflow/rest/v1/springweb/SpringWebResource.java
- nflow-rest-api-spring-web/src/main/java/io/nflow/rest/v1/springweb/StatisticsResource.java
- nflow-rest-api-spring-web/src/main/java/io/nflow/rest/v1/springweb/WorkflowDefinitionResource.java
- nflow-rest-api-spring-web/src/main/java/io/nflow/rest/v1/springweb/WorkflowExecutorResource.java
- nflow-rest-api-spring-web/src/main/java/io/nflow/rest/v1/springweb/WorkflowInstanceResource.java
- nflow-rest-api-spring-web/src/test/java/io/nflow/rest/v1/springweb/SpringWebResourceTest.java
Currently when using nflow-netty, the netty EventLoop thread blocks during synchronous JDBC database access. Fix this by introducing a separate thread pool for REST API calls.
> Use dedicated thread pool for blocking database access

- CHANGELOG.md
- nflow-explorer/Gruntfile.js
- nflow-explorer/src/app/app.js
- nflow-explorer/src/app/layout/footer.html
- nflow-explorer/src/app/layout/header.html
- nflow-explorer/src/app/layout/layout.js
- nflow-explorer/src/app/workflow/workflow.html
- nflow-explorer/src/app/workflow/workflowInfo.html
- nflow-explorer/src/app/workflow/workflowInfo.js
- nflow-explorer/src/config.js
- nflow-explorer/src/styles/main.scss
1. Add hooks for customizing Explorer look through config.js (header logo, hide footer, change HTML title)
2. New look for workflow instance properties (previous made your eyes bleed). Also changed the order a bit and removed redundant workflow instance id (it was shown after workflow definion name already)
3. Layout of workflow instance properties and graph changed. Usually everything (properties, graph, tabs) fit "on the same line", but for large workflows (>15 states) rendering remains as it was (graph below workflow instance properties)
4. Separate ugly link from workflow instance page removed and workflow type name converted to a link.
> Minor explorer tuning

- CHANGELOG.md
- nflow-netty/src/test/java/io/nflow/netty/StartNflowTest.java
- nflow-rest-api-common/src/main/java/io/nflow/rest/v1/ResourceBase.java
- nflow-rest-api-spring-web/src/main/java/io/nflow/rest/v1/springweb/SpringWebResource.java
Currently (at least) `NflowNotFoundException`s seem to get mapped to 500 instead of 404.
> Fix webflux error handling

- CHANGELOG.md
- nflow-explorer/src/app/config/routes.js
- nflow-explorer/src/app/search/criteriaModel.js
- nflow-explorer/src/app/search/search.js
- nflow-explorer/src/app/search/searchForm.js
- nflow-explorer/test/spec/search/criteriaModel.js
- nflow-explorer/test/spec/search/search.js
- nflow-explorer/test/spec/search/searchForm.js
Set the workflow instance query parameters to state, when search button is pressed. This again sets the parameters to URL, and reloads the search controller with the new query parameters, that are automatically used for making the actual query. When navigating away from the search page, browser back-button will work and the previous query result will be again rendered.
There's a corner case when first opening search page vs. searching without any criteria. The latter is handled by fake workflow definition type "all", which is ignored as a query parameter, but whose presence forces the search page to make the REST call.
> Persist workflow instance query parameters to URL

- CHANGELOG.md
- nflow-engine/src/main/java/io/nflow/engine/internal/dao/WorkflowInstanceDao.java
**Background:** 
With the number of actions growing for a workflow in `nflow_workflow_actions` and `nflow_workflow_states` tables, a workflow can no longer load on nflow ui, because below end point timesout -
`/nflow/api/v1/workflow-instance/id/{workflowId}?include=actions,currentStateVariables,actionStateVariables`
With below state of cardinality of the table, it took 1 min 22 sec to get the result from the query this PR touches.
```
SHOW INDEX FROM nflow_workflow_state;
+----------------------+------------+----------+
| Column_name | Collation | Cardinality |
+----------------------+------------+----------+
| workflow_id | A         |     3762445 |
| action_id   | A         |     7524890 |
| state_key   | A         |     7524890 |
```
**Solution**
This PR adds `workflow_id` to the query …
> Use workflowId to query the results in nflow_workflow_state

- CHANGELOG.md
- nflow-engine/src/main/java/io/nflow/engine/internal/workflow/WorkflowDefinitionScanner.java
- nflow-engine/src/test/java/io/nflow/engine/internal/executor/WorkflowStateProcessorTest.java
Check for duplicate state var names.
Add instantiation for common collection interfaces
Fixes #527
> Allow generics inside Mutable. 

- CHANGELOG.md
- pom.xml
Ensures that we are compiling using JDK 11 version of APIs. Also allows building when using JDK 17.
https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-release.html
https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-source-and-target.html
> Define maven.compiler.release=11

- .github/workflows/build.yaml
- .github/workflows/codeql-analysis.yml
Enables the github provided CodeQL analysis, results are visible in Security tab
Tunes the normal build to use newer versions of imported actions and adds some security settings to limit rights of the build.
> Try CodeQL analysis

- CHANGELOG.md
- nflow-engine/src/main/java/io/nflow/engine/config/db/DatabaseConfiguration.java
- nflow-engine/src/main/java/io/nflow/engine/internal/executor/WorkflowDispatcher.java
- nflow-engine/src/main/java/io/nflow/engine/internal/executor/WorkflowStateProcessor.java
- nflow-engine/src/main/java/io/nflow/engine/internal/workflow/StoredWorkflowDefinition.java
- nflow-engine/src/main/java/io/nflow/engine/internal/workflow/StoredWorkflowDefinitionWrapper.java
- nflow-engine/src/main/java/io/nflow/engine/service/WorkflowDefinitionService.java
- nflow-engine/src/main/java/io/nflow/engine/workflow/definition/WorkflowDefinition.java
- nflow-engine/src/main/resources/nflow-engine.properties
- nflow-engine/src/test/java/io/nflow/engine/internal/executor/WorkflowDispatcherTest.java
- nflow-engine/src/test/java/io/nflow/engine/internal/executor/WorkflowStateProcessorTest.java
- nflow-engine/src/test/java/io/nflow/engine/service/WorkflowDefinitionServiceTest.java
- nflow-engine/src/test/java/io/nflow/engine/service/WorkflowDefinitionServiceWithSpringTest.java
- nflow-engine/src/test/resources/junit.properties
- nflow-engine/src/test/resources/nflow-engine-test.properties
- nflow-server-common/src/main/java/io/nflow/server/spring/NflowStandardEnvironment.java
- nflow-tests/src/test/java/io/nflow/tests/CodelessEngineTest.java
- nflow-tests/src/test/java/io/nflow/tests/SkipAutoStartTest.java
- nflow-tests/src/test/java/io/nflow/tests/extension/NflowServerConfig.java
The maximum rate can be controller with `nflow.definition.loadMissingFromDatabaseSeconds` - default rate is once every 60 seconds. But the definitions are only loaded from database if needed, not constantly in the background.
> Support loading workflow definitions from database

- nflow-explorer-ng/src/utils.ts
Changes date format for nflow-explorer-ng to `HH`, previously `KK`
> Changes date format as per #583 discussion

- CHANGELOG.md
- nflow-explorer-ng/src/workflow-instance/WorkflowInstanceSearchForm.tsx
`WorkflowInstanceResource` parameter is `parentWorkflowId` and not `parentInstanceId`
> Fix UI querying with parent workflow id

- CHANGELOG.md
- nflow-rest-api-common/src/main/java/io/nflow/rest/config/RestConfiguration.java
Remove `@Primary` annotation from `nflowRestObjectMapper` in `RestConfiguration` to allow overriding default mapper. Spring Boot applications may need to define the mapper explicitly now.
Fixes #567
> Remove primary annotation from rest object mapper

- CHANGELOG.md
- nflow-explorer-ng/src/workflow-instance/WorkflowInstanceDetailsPage.tsx
Fix child workflow not loading custom instance content
> Fix child workflow not loading custom instance content

- CHANGELOG.md
- nflow-engine/src/main/java/io/nflow/engine/config/EngineConfiguration.java
- nflow-engine/src/main/java/io/nflow/engine/guice/EngineModule.java
- nflow-engine/src/main/java/io/nflow/engine/internal/dao/WorkflowDefinitionDao.java
- nflow-engine/src/main/java/io/nflow/engine/internal/workflow/ObjectStringMapper.java
- nflow-engine/src/test/java/io/nflow/engine/config/EngineConfigurationTest.java
- nflow-engine/src/test/java/io/nflow/engine/guice/EngineModuleTest.java
- nflow-engine/src/test/java/io/nflow/engine/internal/dao/DaoTestConfiguration.java
- nflow-engine/src/test/java/io/nflow/engine/internal/executor/WorkflowStateProcessorTest.java
- nflow-engine/src/test/java/io/nflow/engine/internal/workflow/ObjectStringMapperTest.java
- nflow-examples/spring-boot/full-stack-kotlin/src/NflowApplication.kt
- nflow-examples/spring-boot/full-stack/gradle/src/main/java/io/nflow/springboot/fullstack/gradle/DemoApplication.java
- nflow-examples/spring-boot/full-stack/maven/src/main/java/io/nflow/springboot/fullstack/maven/DemoApplication.java
- nflow-rest-api-common/src/main/java/io/nflow/rest/config/RestConfiguration.java
- nflow-rest-api-common/src/test/java/io/nflow/rest/v1/converter/CreateWorkflowConverterTest.java
- nflow-rest-api-jax-rs/src/test/java/io/nflow/rest/v1/config/jaxrs/RestConfigurationTest.java
- nflow-rest-api-jax-rs/src/test/java/io/nflow/rest/v1/jaxrs/WorkflowInstanceResourceTest.java
Provide `ObjectMapper` defined in `EngineConfiguration` via custom interface to avoid collision with the one in `RestConfiguration` and remove need for `Primary` annotation usage.
> Provide engine ObjectMapper via custom interface

- nflow-explorer/src/workflow-instance/manage/UpdateWorkflowInstanceSignalForm.tsx
- nflow-explorer/src/workflow-instance/manage/UpdateWorkflowInstanceStateForm.tsx
- nflow-explorer/src/workflow-instance/manage/UpdateWorkflowInstanceStateVariableForm.tsx
with reference to this issue logged
https://github.com/NitorCreations/nflow/issues/629
Below screenshots showing the behaviour after the change
> Add an http status check on form updates as they default to success when it could fail

- nflow-explorer/src/workflow-instance/StateVariableTable.tsx
…/nflow/issues/638
ref the above issue, small change to display the state variables in order of the key, below examples after making the code change
> nflow explorer | sort the state variables by key on the display

- CHANGELOG.md
- nflow-explorer/src/component/StateGraph.jsx
- nflow-explorer/src/component/StateGraph.scss
- nflow-explorer/src/workflow-instance/WorkflowInstanceDetailsPage.tsx
can change the colours or what is wanted in the css file, the logic is done for the indications.
sample below, red text and underline for current state, then any state-state the arrow is also hi-lighted
> enhance graph to indicate workflow steps and show active state

- README.md
Let's promote the commercial support aspect in GitHub (it is also in nflow.io).
> doc: commercial support in README.md

- nflow-explorer/src/component/StateGraph.jsx
Actions can be empty for an instance for example  when creating a lot of workflows with no activation time, that are then managed by their parent workflow that activates them when more work is needed.
Without this check, these workflows waiting for activation crash the explorer.
> Size check actions array in StateGraph
