CHANGELOG.md
nflow-engine/src/main/java/com/nitorcreations/nflow/engine/internal/dao/PollingRaceConditionException.java
nflow-engine/src/main/java/com/nitorcreations/nflow/engine/internal/dao/WorkflowInstanceDao.java
nflow-engine/src/test/java/com/nitorcreations/nflow/engine/internal/dao/WorkflowInstanceDaoTest.java

Instead of full rollback when a race condition with another workflow ins...

Partial polling of workflow instances

---

CHANGELOG.md
DECISION_LOG.md
nflow-engine/src/main/java/com/nitorcreations/nflow/engine/internal/dao/WorkflowInstanceDao.java
nflow-engine/src/main/java/com/nitorcreations/nflow/engine/internal/storage/db/H2DatabaseConfiguration.java
nflow-engine/src/main/java/com/nitorcreations/nflow/engine/internal/storage/db/MysqlDatabaseConfiguration.java
nflow-engine/src/main/java/com/nitorcreations/nflow/engine/internal/storage/db/PgDatabaseConfiguration.java
nflow-engine/src/main/java/com/nitorcreations/nflow/engine/internal/storage/db/SQLVariants.java
nflow-rest-api/src/main/java/com/nitorcreations/nflow/rest/v1/WorkflowInstanceResource.java
nflow-tests/src/test/java/com/nitorcreations/nflow/tests/AbstractNflowTest.java
nflow-tests/src/test/java/com/nitorcreations/nflow/tests/DemoWorkflowTest.java
nflow-tests/src/test/java/com/nitorcreations/nflow/tests/FutureWorkflowTest.java

Use update returning for postgresql to move polling concurrency handling to db

---

nflow-engine/src/main/java/com/nitorcreations/nflow/engine/internal/dao/WorkflowDefinitionDao.java
nflow-engine/src/main/resources/scripts/db/h2.create.ddl.sql
nflow-engine/src/main/resources/scripts/db/mysql.create.ddl.sql
nflow-engine/src/main/resources/scripts/db/mysql.legacy.create.ddl.sql
nflow-engine/src/main/resources/scripts/db/postgresql.create.ddl.sql
nflow-engine/src/main/resources/scripts/db/update-1.2.0-x/h2.update.ddl.sql
nflow-engine/src/main/resources/scripts/db/update-1.2.0-x/mysql.legacy.update.ddl.sql
nflow-engine/src/main/resources/scripts/db/update-1.2.0-x/mysql.update.ddl.sql
nflow-engine/src/main/resources/scripts/db/update-1.2.0-x/postgresql.update.ddl.sql

Field contains SHA1 digest of serialized workflow definition. The field
can be used e.g. quickly detect if definition has changed.

Add field nflow_workflow_definition.definition_sha1.

---

nflow-engine/src/main/java/com/nitorcreations/nflow/engine/internal/storage/db/DatabaseConfiguration.java

... and available in spring context

Register hikari pool to MetricRegistry if MetricRegistry is on classpath

---

nflow-engine/src/main/java/com/nitorcreations/nflow/engine/internal/dao/WorkflowDefinitionDao.java
nflow-engine/src/main/java/com/nitorcreations/nflow/engine/internal/executor/WorkflowStateProcessor.java
nflow-engine/src/main/java/com/nitorcreations/nflow/engine/internal/workflow/WorkflowDefinitionScanner.java
nflow-engine/src/main/java/com/nitorcreations/nflow/engine/listener/WorkflowExecutorListener.java
nflow-engine/src/main/java/com/nitorcreations/nflow/engine/service/WorkflowDefinitionService.java
nflow-engine/src/main/java/com/nitorcreations/nflow/engine/service/WorkflowInstanceService.java
nflow-engine/src/main/java/com/nitorcreations/nflow/engine/workflow/definition/AbstractWorkflowDefinition.java
nflow-engine/src/test/java/com/nitorcreations/nflow/engine/internal/executor/WorkflowDispatcherTest.java
nflow-engine/src/test/java/com/nitorcreations/nflow/engine/internal/storage/db/DatabaseInitializerTest.java
nflow-engine/src/test/java/com/nitorcreations/nflow/engine/service/WorkflowDefinitionServiceTest.java
nflow-engine/src/test/java/com/nitorcreations/nflow/engine/service/WorkflowDefinitionServiceWithSpringTest.java
nflow-perf-test/src/main/java/com/nitorcreations/nflow/performance/testdata/TestDataGenerator.java
nflow-rest-api/src/main/java/com/nitorcreations/nflow/rest/v1/WorkflowDefinitionResource.java
nflow-rest-api/src/main/java/com/nitorcreations/nflow/rest/v1/converter/ListWorkflowDefinitionConverter.java
nflow-tests/.settings/org.eclipse.core.resources.prefs

This changes no functionality except for the single bugfix in WorkflowInstanceService

Switch from using WorkflowDefinition to using AbstractWorkflowDefintion

---

nflow-engine/src/main/java/com/nitorcreations/nflow/engine/internal/dao/DaoUtil.java
nflow-engine/src/main/java/com/nitorcreations/nflow/engine/internal/dao/ExecutorDao.java
nflow-engine/src/main/java/com/nitorcreations/nflow/engine/internal/dao/WorkflowInstanceDao.java
nflow-engine/src/main/resources/scripts/db/h2.create.ddl.sql
nflow-engine/src/main/resources/scripts/db/mysql.create.ddl.sql
nflow-engine/src/main/resources/scripts/db/mysql.legacy.create.ddl.sql
nflow-engine/src/main/resources/scripts/db/postgresql.create.ddl.sql
nflow-engine/src/main/resources/scripts/db/update-1.3.0-x/h2.update.ddl.sql
nflow-engine/src/main/resources/scripts/db/update-1.3.0-x/mysql.legacy.update.ddl.sql
nflow-engine/src/main/resources/scripts/db/update-1.3.0-x/mysql.update.ddl.sql
nflow-engine/src/main/resources/scripts/db/update-1.3.0-x/postgresql.update.ddl.sql

read length from db and cut host string to fit into field

increase executor host length to 253 characters in db

---

nflow-jetty/src/main/java/com/nitorcreations/nflow/jetty/StartNflow.java

e.g.  -Dnflow.jetty.accesslog.directory=/some/dir

Configure nflow-jetty accesslog directory with system property

---

nflow-engine/src/main/java/com/nitorcreations/nflow/engine/internal/dao/HealthCheckDao.java
nflow-engine/src/main/java/com/nitorcreations/nflow/engine/service/HealthCheckService.java
nflow-engine/src/test/java/com/nitorcreations/nflow/engine/internal/dao/DaoTestConfiguration.java
nflow-engine/src/test/java/com/nitorcreations/nflow/engine/internal/dao/HealthCheckDaoTest.java
nflow-engine/src/test/java/com/nitorcreations/nflow/engine/service/HealthCheckServiceTest.java
nflow-engine/src/test/java/com/nitorcreations/nflow/engine/service/WorkflowDefinitionServiceWithSpringTest.java
nflow-jetty/pom.xml
nflow-jetty/src/main/java/com/nitorcreations/nflow/jetty/StartNflow.java
nflow-jetty/src/main/java/com/nitorcreations/nflow/jetty/config/MetricsConfiguration.java
nflow-jetty/src/main/java/com/nitorcreations/nflow/jetty/config/NflowJettyConfiguration.java
nflow-jetty/src/main/java/com/nitorcreations/nflow/jetty/servlet/MetricsServletContextListener.java
nflow-jetty/src/test/java/com/nitorcreations/nflow/jetty/StartNflowTest.java
nflow-metrics/pom.xml
nflow-metrics/src/main/java/com/nitorcreations/nflow/metrics/DatabaseConnectionHealthCheck.java
nflow-metrics/src/main/java/com/nitorcreations/nflow/metrics/NflowMetricsContext.java
nflow-metrics/src/test/java/com/nitorcreations/nflow/metrics/DatabaseConnectionHealthCheckTest.java
nflow-metrics/src/test/java/com/nitorcreations/nflow/metrics/MetricsWorkflowExecutorListenerTest.java
nflow-tests/pom.xml
nflow-tests/src/test/java/com/nitorcreations/nflow/tests/MetricsAdminServletTest.java
pom.xml

Healtchecks are implemented using https://dropwizard.github.io/metrics/3.1.0/manual/healthchecks/
Also added servlet that provides a view to healt checks and metrics.

Implement health checks for nflow-jetty.

---

nflow-engine/src/main/java/com/nitorcreations/nflow/engine/service/WorkflowInstanceService.java
nflow-engine/src/main/java/com/nitorcreations/nflow/engine/workflow/instance/QueryWorkflowInstances.java
nflow-engine/src/test/java/com/nitorcreations/nflow/engine/internal/dao/WorkflowInstanceDaoTest.java
nflow-rest-api/pom.xml
nflow-rest-api/src/main/java/com/nitorcreations/nflow/rest/v1/WorkflowDefinitionResource.java
nflow-rest-api/src/main/java/com/nitorcreations/nflow/rest/v1/WorkflowInstanceResource.java
nflow-rest-api/src/test/java/com/nitorcreations/nflow/rest/JerseyCompabilityTest.java
nflow-rest-api/src/test/java/com/nitorcreations/nflow/rest/v1/WorkflowDefinitionResourceTest.java
nflow-rest-api/src/test/java/com/nitorcreations/nflow/rest/v1/WorkflowInstanceResourceTest.java
nflow-tests/src/main/java/com/nitorcreations/nflow/tests/demo/DemoServer.java
nflow-tests/src/main/java/com/nitorcreations/nflow/tests/demo/FibonacciWorkflow.java
pom.xml

CXF allows them, but Jersey doesn't. Replaced all array @QueryParams
with Lists.

Arrays are not permitted @QueryParams in JAX-RS.

---

nflow-engine/src/main/java/com/nitorcreations/nflow/engine/internal/dao/WorkflowInstanceDao.java
nflow-engine/src/test/java/com/nitorcreations/nflow/engine/internal/dao/WorkflowInstanceDaoTest.java
nflow-tests/src/test/java/com/nitorcreations/nflow/tests/ArchiveTest.java

Change < to <= in instance polling condition

---

nflow-engine/src/main/java/com/nitorcreations/nflow/engine/internal/util/PeriodicLogger.java
nflow-engine/src/main/java/com/nitorcreations/nflow/engine/service/ArchiveService.java
nflow-engine/src/test/java/com/nitorcreations/nflow/engine/internal/util/PeriodicLoggerTest.java

+ micro-optimize by using long instead of Long for previous logging value

Add support for loggin warnings to PeriodicLogger. 

---

nflow-tests/pom.xml
nflow-tests/src/test/java/io/nflow/tests/runner/NflowServerRule.java
pom.xml

Only start postgresql if postgresql profile is enabled

Launch embedded postgresql during tests

---

nflow-engine/src/main/java/io/nflow/engine/internal/dao/WorkflowInstanceDao.java
nflow-engine/src/main/java/io/nflow/engine/internal/executor/WorkflowDispatcher.java
nflow-engine/src/main/java/io/nflow/engine/service/WorkflowDefinitionService.java
nflow-engine/src/test/java/io/nflow/engine/internal/executor/WorkflowDispatcherTest.java
nflow-tests/src/test/java/io/nflow/tests/SkipAutoStartTest.java

Related:
https://github.com/NitorCreations/nflow/pull/228

Remove @PostProcess that causes database access before start()

---

nflow-jetty/pom.xml
nflow-jetty/src/main/java/io/nflow/jetty/config/NflowJettyConfiguration.java
nflow-metrics/pom.xml
nflow-perf-test/pom.xml
nflow-perf-test/src/main/java/io/nflow/performance/client/PerfTestConfiguration.java
nflow-rest-api-jax-rs/pom.xml
nflow-tests/src/test/java/io/nflow/tests/config/RestClientConfiguration.java
nflow-tests/src/test/java/io/nflow/tests/runner/NflowServerRule.java
pom.xml

Both jersey and cxf had some functionality moved to new artifacts so add them as deps where needed.

Update dependency versions

---

nflow-metrics/pom.xml
nflow-metrics/src/main/java/io/nflow/metrics/NflowMetricsContext.java
nflow-tests/src/test/java/io/nflow/tests/runner/NflowServerRule.java
pom.xml

- only major bump is metrics 3.2 -> 4.0
- also spring 5.x bug fixes might be useful for many

Version bump

---

nflow-engine/src/main/java/io/nflow/engine/service/WorkflowDefinitionService.java
nflow-jetty/pom.xml
nflow-metrics/pom.xml
nflow-rest-api-jax-rs/pom.xml
pom.xml

- One actual code change to fix deprecation warning
- need 3 more packages that are now recommended to be used as external dependencies

Fix code to compile and work on java9 & java10

---

nflow-rest-api-spring-web/src/main/java/io/nflow/rest/v1/springweb/StatisticsResource.java
nflow-rest-api-spring-web/src/main/java/io/nflow/rest/v1/springweb/WorkflowDefinitionResource.java
nflow-rest-api-spring-web/src/main/java/io/nflow/rest/v1/springweb/WorkflowInstanceResource.java
pom.xml

Also run nflow-jetty before nflow-netty during build as jetty is more stablie than netty, and catches real problems earlier and more reliably.

Fix spring-web @RequestParam required to false

---

nflow-netty/pom.xml
nflow-netty/src/main/java/io/nflow/netty/StartNflow.java
nflow-server-common/src/test/java/io/nflow/server/spring/NflowStandardEnvironmentTest.java
pom.xml

Update Spring 5.1.0. This fixes some warnings when running with JDK 10.

Spring 5.1.0

---

CHANGELOG.md
nflow-netty/src/main/java/io/nflow/netty/StartNflow.java
nflow-netty/src/test/java/io/nflow/netty/StartNflowTest.java
nflow-netty/src/test/resources/external.properties

Also: now it's possibly to specify the port programmatically which makes it possible to get around port conflicts

Change nflow-netty's StartNflow interface to match nflow-jetty's

---

release.sh

This release was created using the script below: https://github.com/NitorCreations/nflow/releases/tag/5.3.1
```
#!/bin/bash
RELEASE_VERSION=5.3.1
PREVIOUS_VERSION=5.3.0
prompt_continue() {
echo
echo "Next: $1"
read -p "Press enter to continue..."
}
if [[ -e .github_api_token ]]; then
prompt_continue "Creating Github API release for $RELEASE_VERSION"
RELEASE_DESC_START=$(grep -n "## $RELEASE_VERSION" CHANGELOG.md | cut -f1 -d:)
RELEASE_DESC_END=$(grep -n "## $PREVIOUS_VERSION" CHANGELOG.md | cut -f1 -d:)
RELEASE_DESC=$(cat CHANGELOG.md | awk -v desc_start="$RELEASE_DESC_START" -v desc_end="$RELEASE_DESC_END" 'NR > desc_start+1 && NR < desc_end-1 {printf "%s\\n", $0}')
GITHUB_API_TOKEN=$(cat .github_api_token)
curl -v -X POST -H "Authorization: token $GITHUB_API_TOKEN" -H "Content-Type: …
```

Github API release using API [ci skip]

---

CHANGELOG.md
nflow-explorer/bower.json
nflow-explorer/package-lock.json
nflow-explorer/package.json

Including lodash 4.17.11. Earlier lodash version had this security issue https://nvd.nist.gov/vuln/detail/CVE-2018-16487

Some library updated for nflow-explorer

---

CHANGELOG.md
pom.xml

Library updates

---

CHANGELOG.md
nflow-explorer/package-lock.json
nflow-explorer/package.json

https://nvd.nist.gov/vuln/detail/CVE-2018-16492

extend 3.0.2

---

CHANGELOG.md
nflow-explorer/CHANGELOG.md
nflow-explorer/src/app/components/customContent.html
nflow-explorer/src/app/components/customContent.js
nflow-explorer/src/app/components/index.js
nflow-explorer/src/app/workflow-definition/workflowDefinition.html
nflow-explorer/src/app/workflow-definition/workflowDefinition.js
nflow-explorer/src/app/workflow/workflow.html
nflow-explorer/src/app/workflow/workflowInfo.html
nflow-explorer/src/app/workflow/workflowInfo.js
nflow-explorer/src/config.js
nflow-explorer/src/index.html

Users can now add custom Javascript functions to config.js. Those functions are invoked when rendering workflow definition and workflow instance page and output of the function is displayed on the page.

Show user defined content in ui

---

CHANGELOG.md
nflow-netty/src/main/java/io/nflow/netty/StartNflow.java
nflow-netty/src/test/java/io/nflow/netty/StartNflowTest.java

Bonus: use plural form in varags.

Add support for adding ApplicationListener when starting netty

---

CHANGELOG.md
nflow-explorer/bower.json
nflow-explorer/package-lock.json
nflow-explorer/package.json
nflow-explorer/pom.xml
nflow-explorer/test/karma.conf.js

Update libraries for nFlow Explorer. Includes fix for morgan library security issue.
- https://github.com/NitorCreations/nflow/network/alert/nflow-explorer/package-lock.json/morgan/open
Fix travis build to actually run unit tests for nflow-explorer module.

nFlow Explorer: Library updates and fix build.

---

nflow-engine/src/main/java/io/nflow/engine/NflowEngine.java
nflow-engine/src/main/java/io/nflow/engine/internal/dao/ArchiveDao.java
nflow-engine/src/main/java/io/nflow/engine/internal/dao/ExecutorDao.java
nflow-engine/src/main/java/io/nflow/engine/internal/dao/HealthCheckDao.java
nflow-engine/src/main/java/io/nflow/engine/internal/dao/StatisticsDao.java
nflow-engine/src/main/java/io/nflow/engine/internal/dao/TableMetadataChecker.java
nflow-engine/src/main/java/io/nflow/engine/internal/dao/WorkflowDefinitionDao.java
nflow-engine/src/main/java/io/nflow/engine/internal/dao/WorkflowInstanceDao.java
nflow-engine/src/main/java/io/nflow/engine/internal/workflow/WorkflowInstancePreProcessor.java
nflow-engine/src/main/java/io/nflow/engine/service/ArchiveService.java
nflow-engine/src/main/java/io/nflow/engine/service/StatisticsService.java
nflow-engine/src/main/java/io/nflow/engine/service/WorkflowInstanceService.java
nflow-engine/src/test/java/io/nflow/engine/NflowEngineTest.java
nflow-engine/src/test/java/io/nflow/engine/internal/dao/DaoTestConfiguration.java
nflow-engine/src/test/java/io/nflow/engine/internal/dao/WorkflowInstanceDaoTest.java
nflow-engine/src/test/java/io/nflow/engine/service/ArchiveServiceTest.java
nflow-engine/src/test/java/io/nflow/engine/service/StatisticsServiceTest.java
nflow-engine/src/test/java/io/nflow/engine/service/WorkflowInstanceServiceTest.java

Makes using the component easier in non-spring environment.

Replace property injection with constructor injection

---

CHANGELOG.md
nflow-engine/src/main/java/io/nflow/engine/internal/executor/WorkflowStateProcessor.java

Add workflow id to errors if saveWorkflowInstanceState() fails

Improve logging WorkflowStateProcessor

---

CHANGELOG.md
nflow-explorer/bower.json
nflow-explorer/src/index.html

In 3.6.1 the line from index.html is removed which means the code isn't packaged.

Downgrade svg-pan-zoom to 3.6.0 because 3.6.1 doesn't work with bower

---

nflow-engine/src/main/resources/scripts/db/update-5.7.0-x/mysql.legacy.update.ddl.sql
nflow-engine/src/main/resources/scripts/db/update-5.7.0-x/mysql.update.ddl.sql

https://dev.mysql.com/doc/refman/5.7/en/drop-index.html

Fix mysql DROP INDEX requires "ON [table]"

---

CHANGELOG.md
nflow-engine/src/main/java/io/nflow/engine/config/db/Db2DatabaseConfiguration.java
nflow-engine/src/main/java/io/nflow/engine/config/db/H2DatabaseConfiguration.java
nflow-engine/src/main/java/io/nflow/engine/config/db/OracleDatabaseConfiguration.java
nflow-engine/src/main/java/io/nflow/engine/config/db/PgDatabaseConfiguration.java
nflow-engine/src/main/java/io/nflow/engine/config/db/SqlServerDatabaseConfiguration.java
nflow-engine/src/main/java/io/nflow/engine/internal/dao/MaintenanceDao.java
nflow-engine/src/main/java/io/nflow/engine/internal/dao/WorkflowInstanceDao.java
nflow-engine/src/main/java/io/nflow/engine/internal/storage/db/MySQLVariants.java
nflow-engine/src/main/java/io/nflow/engine/internal/storage/db/SQLVariants.java
nflow-engine/src/test/java/io/nflow/engine/internal/dao/WorkflowInstanceDaoTest.java
nflow-tests/src/test/java/io/nflow/tests/ConcurrentEnginesTest.java
nflow-tests/src/test/java/io/nflow/tests/extension/NflowServerConfig.java

Fixes a deadlock observed when multiple engines are running concurrently

Use for update skip locked for postgresql polling

---

CHANGELOG.md
pom.xml

http://mailman.qos.ch/pipermail/announce/2021/000164.html
https://jira.qos.ch/browse/LOGBACK-1591

Upgrade logback-classic to 1.2.8

---

scripts/setup-db-db2.sh
scripts/setup-db-mariadb.sh
scripts/setup-db-postgresql.sh
scripts/setup-db-sqlserver.sh

* db2: 11.5.0->11.5.7
* mariadb 10.7->10.8
* sqlserver 2019->2022

Bump latest versions of databases to test against: 

---

nflow-engine/src/main/java/io/nflow/engine/workflow/definition/WorkflowSettings.java
nflow-examples/spring-boot/bare-minimum/gradle/build.gradle
nflow-examples/spring-boot/bare-minimum/maven/pom.xml
nflow-examples/spring-boot/full-stack-kotlin/build.gradle.kts
nflow-examples/spring-boot/full-stack-kotlin/resources/static/explorer/config.js
nflow-examples/spring-boot/full-stack/gradle/build.gradle
nflow-examples/spring-boot/full-stack/gradle/src/main/java/io/nflow/springboot/fullstack/gradle/DemoApplication.java
nflow-examples/spring-boot/full-stack/gradle/src/main/resources/static/explorer/config.js
nflow-examples/spring-boot/full-stack/maven/pom.xml
nflow-examples/spring-boot/full-stack/maven/src/main/java/io/nflow/springboot/fullstack/maven/DemoApplication.java
nflow-examples/spring-boot/full-stack/maven/src/main/resources/static/explorer/config.js
nflow-explorer-ng/src/component/Spinner.tsx

Fix minor issues from multiple modules.

Fix misc issues

---

.github/workflows/build.yaml
.gitignore
CHANGELOG.md
nflow-engine/src/main/java/io/nflow/engine/config/db/OracleDatabaseConfiguration.java
nflow-engine/src/main/java/io/nflow/engine/internal/dao/WorkflowInstanceDao.java
nflow-engine/src/main/java/io/nflow/engine/internal/storage/db/SQLVariants.java
nflow-engine/src/main/resources/nflow-engine.properties
nflow-jetty/pom.xml
nflow-netty/pom.xml
nflow-tests/pom.xml
nflow-tests/src/test/java/io/nflow/tests/StateVariablesTest.java
pom.xml
scripts/setup-db-db2.sh
scripts/setup-db-oracle.sh

I first tried with the official oracle xe docker image from here:
https://container-registry.oracle.com/ords/f?p=113:4:8599516864664:::4:P4_REPOSITORY,AI_REPOSITORY,AI_REPOSITORY_NAME,P4_REPOSITORY_NAME,P4_EULA_ID,P4_BUSINESS_AREA_ID:803,803,Oracle%20Database%20Express%20Edition,Oracle%20Database%20Express%20Edition,1,0&cs=3VNb-DExMb_jEYiR4HbMvaPuI7zLe1hTekTLgQWlniKig4Dcl12Spn7ggawIAyf7KkZ09wnGKTn5iyGOX1_b79w
Managed to get it running, but never managed to connect to it using jdbc from outside the docker.

Oracle now has jdbc driver in maven repo and at least some commonly used xe db in docker hub.

---

.github/workflows/build.yaml
nflow-jetty/pom.xml
nflow-netty/pom.xml
nflow-tests/pom.xml
pom.xml
scripts/setup-db-db2.sh

It was disabled when migrating from travis to github actions.

DB2 integration test re-enable

---

nflow-engine/src/main/resources/nflow-engine.properties
scripts/setup-db-sqlserver.sh

Fix sqlserver password env variable and make password stronger

---

.markdownlint.json
CHANGELOG.md
DECISION_LOG.md
nflow-explorer-ng/.markdownlint.json
nflow-explorer-ng/README.md

Add lint configs for markdown

---

CHANGELOG.md
nflow-explorer-ng/src/component/ObjectTable.tsx

Fix ObjectTable to show false props

Fix ObjectTable to show false props

---

nflow-explorer/src/service.ts

Refer to this issue: https://github.com/NitorCreations/nflow/issues/648

add content type header when not MSAL

---

nflow-explorer/src/component/Selection.tsx

this change makes the selection lists searchable and display in alphabetic order

update selection to be a search select and display in alphabetic order
